### ISSUE TITLE
`use_database_state` hook

### ISSUE THREAD

**Issue by Archmonger** [idom-team/django-idom#39]
### Old Behavior

State is generated on a per-render basis and has no method of being permanently stored.

Additionally, there is no convenient way to perform DB queries within components (as of Django 4.1)

### New Behavior

Allow for persistent state that is databased backed.

### Implementation Details

Persistently store/restore context based on a database model.

The interface should take in a single database object...

```python
from my_django_app.models import GeneralSettings

state, set_state = hooks.use_database_state(GeneralSettings.objects.get(id=20))
state.my_database_field = True

# This saves the values to the database and issues a re-render.
set_state(state)
```

In the background, the set state is doing the following...

```python
def set_state(state):
    state.save()
    ...
```

### Code of Conduct

- [X] I agree to follow the [Code of Conduct](https://github.com/idom-team/django-idom/blob/main/CODE_OF_CONDUCT.md).

**Comment by rmorshea** [comment]
I imagine the usage should look like either:

```python
results = use_database(lambda: Model.objects.all())

@use_database
def results():
    return Model.objects.all()
```

The implementation might look like:

```python
def use_database(function, initial_value=None):
    result, set_result = use_state(initial_value)

    query_function = use_callback(query_function)
    async_function = use_memo(lambda: database_sync_to_async(function))

    @use_effect
    async def exec_function():
        output = await async_function()
        if isinstance(output, QuerySet):
            bool(output)
        set_result(output)

    return result
```

**Comment by Archmonger** [comment]
With that kind of interface, how would someone edit an entry and then save changes?

There needs to be some way of performing `.save()` operations via `database_sync_to_async`

**Comment by rmorshea** [comment]
Wouldn't one typically do that in response to some sort of event, in which case you'd be able to define an async handler that does this?

**Comment by rmorshea** [comment]
You're right though, that does feel a bit disjointed. Maybe the interface ought to be more like `use_state` for single record access.

```python
model, set_model = use_one_model(
    Model.objects.get(...)  # assuming query exec is delayed
)

async def handle_event():
    await set_model(attr=...)
```

**Comment by rmorshea** [comment]
I'm not really sure how this should work for bulk access though...

**Comment by rmorshea** [comment]
Actually, a deeper issue here around object identity. The declarative nature of IDOM and the imperative nature of Django clash here. For example, because Django expects you to modify an object to update it, when re-rendering in IDOM the `model` instance won't change. For example, imagine using a `model` in a `use_memo` hook:

```python
model, set_model = use_one_model(...)
something_expensive = use_memo(lambda: compute_something_expensive(model))
```

In order to know whether `something_expensive` needs to be re-computed, IDOM looks at the identity of `model`. If `model` is the same object, then `something_expensive` won't be re-computed.

It almost feels like there needs to be a thin declarative wrapper around Django's models.

**Comment by Archmonger** [comment]
While Django models might be mutable (haven't confirmed), I know that Django querysets are immutable.

The lazy nature of things is the biggest issue though. I haven't been able to find a good solution to that yet.

Also, the actual construction of a `.objects` call needs to occur when already within a sync context.

I honestly think the best solution to this might end up being a monkey patch to the Django `Model` object...

I've also been planning on PRing some upstream fixes on the Django repo for this sync/async issue.

**Comment by Archmonger** [comment]
Closing this.

I think it no longer makes sense given the existence of `use_query`.
