### ISSUE TITLE
get_component() Utility Function

### ISSUE THREAD

**Issue by Archmonger** [idom-team/django-idom#40]
Make a utility that returns a component given a certain path, if it has been registered.
This already exists to some degree within IDOM (for the templatetag), but needs some massaging to be a public tool.

**Comment by brdhunga** [comment]
I would love to work on this as I think it will be super helpful. If somebody could push me in the right direction, I could give a shot.

**Comment by Archmonger** [comment]
Hey @brdhunga 

This function would essentially be the inverse of our [register function](https://github.com/idom-team/django-idom/blob/main/src/django_idom/utils.py#L19).
