### ISSUE TITLE
Avoid multiple component registrations

### ISSUE THREAD

**Issue by rmorshea** [idom-team/django-idom#5]
Since one can use the same component more than once we should avoid calling `_register_component` more than once if it's already been done. A simple containment check in `IDOM_REGISTERED_COMPONENTS` should work [here](https://github.com/idom-team/django-idom/blob/121f72942e67a54b0539b60de526137769479f2e/src/django_idom/templatetags/idom.py#L21).

**Comment by Archmonger** [comment]
Accidentally commented on the wrong issue before, so I'm reposting here

---

Caching the register function with funcutils.cache would provide the same ability to skip re-registration, and would allow us to skip the sys.modules check. Could be slightly more performant than checking IDOM_REGISTERED_COMPONENTS.

**Comment by Archmonger** [comment]
Note: recently discovered there is no performance reduction for importing a module more than one time. Apparently importlib already does a `sys.modules` check. Which means we can remove [this LOC](https://github.com/idom-team/django-idom/blob/121f72942e67a54b0539b60de526137769479f2e/src/django_idom/templatetags/idom.py#L38)

See [here](https://stackoverflow.com/questions/4177735/best-practice-for-lazy-loading-python-modules) for more details
