### ISSUE TITLE
Add Type Checking To This Project And Add py.typed

### ISSUE THREAD

**Issue by rmorshea** [idom-team/django-idom#91]
### Current Situation

Right now, we don't do any type checking with MyPy. We also do not distribute a `py.typed` marker file which would allow MyPy to work with `django_idom` when it's installed in other projects.

### Proposed Actions

- Add type checking with `mypy`. Preferably we'd eventually check in `--strict` mode, but we don't have to start there.
- Distribute a `py.typed` marker file.

**Comment by Archmonger** [comment]
What's the benefit of MyPy over stdlib type hints?

**Comment by rmorshea** [comment]
[MyPy](http://mypy-lang.org/) is just the type checker. All the type hints will stay the same.
